require:
  - rubocop-rails
  - rubocop-performance

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/bundle"

Documentation:
  Enabled: false

Performance:
  Exclude:
    - "**/test/**/*"

Lint/RedundantCopDisableDirective:
  Exclude:
    - "**/*.*"

Metrics/LineLength:
  Max: 120
  Exclude:
    - config/**/*
    - db/**

Style/Documentation:
  Exclude:
    - db/**/*
    - app/controllers/**/*
    - test/**/*

Rails/BulkChangeTable:
  Exclude:
    - db/migrate/*

Rails/RakeEnvironment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - db/seeds.rb
    - db/migrate/*
    - config/environments/*.rb
    - config/routes.rb
    - lib/tasks/*.rake
    - test/**/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/ClassLength:
  Exclude:
    - test/controllers/**/*
