development:
  adapter: postgresql
  encoding: unicode
  database: carbon_map_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: carbon_map_test
  pool: 5
  username:
  password:

production:
  url: <%= ENV['DATABASE_URL'] %>
